"""Numerical-regression tests against golden snapshots in tests/data/snapshots/.

Purpose: catch unintended numerical drift in refactors. Each test loads a
snapshot (generated by scripts/pm/regenerate_snapshots.py from the
Protenix v1.0.0 weights with a fixed seed) and re-runs the same path
under the current code. If output changes beyond bf16 tolerance, the test
fails — the refactor (or model edit) is changing numerics.

If a change is intentional, regenerate with:
    uv run python scripts/pm/regenerate_snapshots.py --force
and commit the .npz diff alongside the code change.

Requires:
    - CUDA
    - checkpoints/protenix_base_default_v1.0.0.pt
    - tests/data/snapshots/*.npz (committed)
"""

from __future__ import annotations

import sys
from collections import OrderedDict
from pathlib import Path

import numpy as np
import pytest
import torch

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from helico.data import make_synthetic_batch
from helico.model import Helico, HelicoConfig
from helico.model.features import (
    build_ref_features,
    build_relpe_feats,
    build_s_inputs,
    build_msa_raw,
)
from helico.load_protenix import load_protenix_state_dict

SNAPSHOTS_DIR = Path(__file__).resolve().parent / "data" / "snapshots"
CHECKPOINT = REPO / "checkpoints" / "protenix_base_default_v1.0.0.pt"
TESTS_DATA = Path(__file__).resolve().parent / "data"
CIF_PATH = TESTS_DATA / "1mbn.cif.gz"
A3M_PATH = TESTS_DATA / "1mbn.a3m"
CCD_CACHE = REPO / "data" / "ccd_cache.pkl"
if not CCD_CACHE.exists():
    from helico.data import _processed_dir
    CCD_CACHE = _processed_dir() / "ccd_cache.pkl"
SEED = 42
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Tolerance rationale: bf16 has ~8 mantissa bits → ~3.9e-3 relative error
# compounds through dozens of ops. Pre-recycle tensors are close enough
# across GPUs that per-element atol/rtol works. Post-recycle values
# accumulate bf16 noise across 2+ recycle iterations and the noise
# varies per GPU generation (A5000 vs H100 etc.), so we use a
# whole-tensor rel_L2 check instead — robust to cross-GPU noise but
# still catches refactor drift (which would change numerics
# coherently, not just at the edges).
RTOL = 1e-2
ATOL = 5e-2
REL_L2_TOL = 5e-2   # Whole-tensor ‖Δ‖ / ‖expected‖ — used for post-recycle

_PROTENIX_AVAIL = CHECKPOINT.exists() and DEVICE == "cuda"
pytestmark = [
    pytest.mark.numerics,
    pytest.mark.skipif(
        not _PROTENIX_AVAIL,
        reason=f"Requires CUDA + {CHECKPOINT.name}",
    ),
]


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def protenix_model():
    """Full-size Helico with Protenix v1.0.0 weights loaded. Kept in fp32
    on GPU; inference paths use autocast to bf16."""
    ckpt = torch.load(CHECKPOINT, map_location="cpu", weights_only=False)
    sd = ckpt["model"]
    sd = OrderedDict((k.removeprefix("module."), v) for k, v in sd.items())
    model = Helico(HelicoConfig())
    load_protenix_state_dict(sd, model)
    return model.to(device=DEVICE).eval()


@pytest.fixture(scope="module")
def canonical_batch():
    """Matches scripts/pm/regenerate_snapshots.py::_canonical_batch exactly."""
    torch.manual_seed(SEED)
    batch = make_synthetic_batch(
        n_tokens=16, n_atoms_per_token=4, batch_size=1, device=DEVICE,
    )
    B = batch["token_types"].shape[0]
    N_tok = 16
    n_msa = 8
    batch["msa"] = torch.randint(0, 32, (B, n_msa, N_tok), device=DEVICE, dtype=torch.long)
    batch["msa"][:, 0, :] = batch["restype"]
    batch["deletion_matrix"] = torch.zeros(B, n_msa, N_tok, device=DEVICE, dtype=torch.float32)
    batch["deletion_mean"] = torch.zeros(B, N_tok, device=DEVICE, dtype=torch.float32)
    batch["msa_profile"] = torch.zeros(B, N_tok, 32, device=DEVICE, dtype=torch.float32)
    batch["has_msa"] = torch.ones(B, device=DEVICE, dtype=torch.float32)
    return batch


def _assert_matches(actual: torch.Tensor, expected: np.ndarray, name: str):
    """Element-wise tolerance check.

    Uses atol OR rtol — i.e., an element passes if EITHER the absolute
    diff is under atol OR the relative diff is under rtol. This handles
    both large- and small-magnitude elements. Appropriate for tensors
    that should match closely across machines (pre-recycle values,
    feature-builder outputs).
    """
    a = actual.detach().to(dtype=torch.float32, device="cpu").numpy()
    e = expected
    assert a.shape == e.shape, f"{name}: shape mismatch {a.shape} vs {e.shape}"
    diff = np.abs(a - e)
    rel = diff / (np.abs(e) + 1e-8)
    assert diff.max() < ATOL or rel.max() < RTOL, (
        f"{name}: max abs diff {diff.max():.4g} (atol={ATOL}), "
        f"max rel diff {rel.max():.4g} (rtol={RTOL}). "
        f"mean={a.mean():.4g} (expected {e.mean():.4g})"
    )


def _assert_matches_rel_l2(actual: torch.Tensor, expected: np.ndarray, name: str,
                            tol: float = REL_L2_TOL):
    """Whole-tensor relative L2 check — robust to cross-GPU noise.

    Computes ‖actual − expected‖_2 / ‖expected‖_2 and asserts it's below
    ``tol``. Unlike per-element max-checks, this summarises the overall
    divergence: a refactor bug typically moves values coherently (big
    rel_L2), while bf16 noise across GPUs only affects tail elements
    (small rel_L2 even if per-element diffs look bad).
    """
    a = actual.detach().to(dtype=torch.float32, device="cpu").numpy()
    e = expected
    assert a.shape == e.shape, f"{name}: shape mismatch {a.shape} vs {e.shape}"
    diff = a.astype(np.float64) - e.astype(np.float64)
    rel_l2 = float(np.linalg.norm(diff) / (np.linalg.norm(e) + 1e-8))
    assert rel_l2 < tol, (
        f"{name}: rel_L2 {rel_l2:.4g} > {tol} "
        f"(actual mean={a.mean():.4g}, std={a.std():.4g}; "
        f"expected mean={e.mean():.4g}, std={e.std():.4g})"
    )


# ---------------------------------------------------------------------------
# Trunk activation snapshot
# ---------------------------------------------------------------------------

class TestTrunkSnapshot:
    """Pin trunk activations (s_inputs, s_init, z_init, post-recycle s/z)
    with Protenix weights + seeded synthetic input. Detects any refactor
    that changes trunk numerics."""

    @pytest.fixture(scope="class")
    def snapshot(self):
        path = SNAPSHOTS_DIR / "trunk.npz"
        assert path.exists(), f"Regenerate with scripts/pm/regenerate_snapshots.py"
        return dict(np.load(path))

    @pytest.fixture(scope="class")
    def actual(self, protenix_model, canonical_batch):
        """Run the trunk path end-to-end, return captured tensors."""
        model = protenix_model
        batch = canonical_batch

        torch.manual_seed(SEED)
        with torch.no_grad(), torch.amp.autocast("cuda", dtype=torch.bfloat16):
            mask = batch.get("token_mask")
            pair_mask = None
            if mask is not None:
                pair_mask = (mask.unsqueeze(-1) & mask.unsqueeze(-2)).float()

            ref_charge, ref_features = build_ref_features(batch)
            atom_mask = batch.get("atom_mask",
                                   torch.ones(1, batch["atom_coords"].shape[1], device=DEVICE))
            atom_mask = atom_mask.float()
            s_inputs = build_s_inputs(model.input_embedder, batch, ref_charge, ref_features, atom_mask)
            s_init = model.linear_sinit(s_inputs)
            z_init = (
                model.linear_zinit1(s_init).unsqueeze(2)
                + model.linear_zinit2(s_init).unsqueeze(1)
            )
            relpe_feats = build_relpe_feats(batch)
            z_init = z_init + model.trunk_relpe(**relpe_feats)
            msa_raw, msa_mask = build_msa_raw(batch)

            s = torch.zeros_like(s_init)
            z = torch.zeros_like(z_init)
            for _ in range(2):  # matches snapshot script N_CYCLES=2
                z = z_init + model.linear_z_cycle(model.layernorm_z_cycle(z))
                z = z + model.template_embedder(batch, z)
                z = model.msa_module(msa_raw, z, s_inputs, msa_mask, pair_mask,
                                      msa_chunk_size=2048)
                s = s_init + model.linear_s(model.layernorm_s(s))
                s, z = model.pairformer(s, z, mask=mask, pair_mask=pair_mask)

        return {
            "s_inputs": s_inputs, "s_init": s_init, "z_init": z_init,
            "s_post_recycle": s, "z_post_recycle": z,
            "ref_charge": ref_charge, "ref_features": ref_features,
            "msa_raw": msa_raw,
        }

    def test_s_inputs(self, snapshot, actual):
        _assert_matches(actual["s_inputs"], snapshot["s_inputs"], "s_inputs")

    def test_s_init(self, snapshot, actual):
        _assert_matches(actual["s_init"], snapshot["s_init"], "s_init")

    def test_z_init(self, snapshot, actual):
        _assert_matches(actual["z_init"], snapshot["z_init"], "z_init")

    def test_s_post_recycle(self, snapshot, actual):
        # Post-recycle tensors accumulate bf16 noise across 2 recycle
        # iterations; noise magnitude varies per-GPU. Use rel_L2.
        _assert_matches_rel_l2(actual["s_post_recycle"], snapshot["s_post_recycle"],
                                "s_post_recycle")

    def test_z_post_recycle(self, snapshot, actual):
        _assert_matches_rel_l2(actual["z_post_recycle"], snapshot["z_post_recycle"],
                                "z_post_recycle")

    def test_ref_charge(self, snapshot, actual):
        _assert_matches(actual["ref_charge"], snapshot["ref_charge"], "ref_charge")

    def test_ref_features(self, snapshot, actual):
        _assert_matches(actual["ref_features"], snapshot["ref_features"],
                        "ref_features")

    def test_msa_raw(self, snapshot, actual):
        _assert_matches(actual["msa_raw"], snapshot["msa_raw"], "msa_raw")


# ---------------------------------------------------------------------------
# Diffusion trajectory snapshot
# ---------------------------------------------------------------------------

class TestDiffusionSnapshot:
    """Pin final diffusion coords (5 EDM steps, seeded trunk+noise)."""

    @pytest.fixture(scope="class")
    def snapshot(self):
        path = SNAPSHOTS_DIR / "diffusion.npz"
        assert path.exists(), f"Regenerate with scripts/pm/regenerate_snapshots.py"
        return dict(np.load(path))

    @pytest.fixture(scope="class")
    def actual(self, protenix_model, canonical_batch):
        model = protenix_model
        batch = canonical_batch

        orig_steps = model.diffusion.n_steps
        model.diffusion.n_steps = 5
        try:
            torch.manual_seed(SEED)
            with torch.no_grad(), torch.amp.autocast("cuda", dtype=torch.bfloat16):
                mask = batch.get("token_mask")
                pair_mask = None
                if mask is not None:
                    pair_mask = (mask.unsqueeze(-1) & mask.unsqueeze(-2)).float()

                ref_charge, ref_features = build_ref_features(batch)
                atom_mask = batch.get("atom_mask",
                                       torch.ones(1, batch["atom_coords"].shape[1], device=DEVICE))
                atom_mask = atom_mask.float()
                s_inputs = build_s_inputs(model.input_embedder, batch, ref_charge, ref_features, atom_mask)
                s_init = model.linear_sinit(s_inputs)
                z_init = (
                    model.linear_zinit1(s_init).unsqueeze(2)
                    + model.linear_zinit2(s_init).unsqueeze(1)
                )
                relpe_feats = build_relpe_feats(batch)
                z_init = z_init + model.trunk_relpe(**relpe_feats)
                msa_raw, msa_mask = build_msa_raw(batch)

                s = torch.zeros_like(s_init)
                z = torch.zeros_like(z_init)
                for _ in range(2):
                    z = z_init + model.linear_z_cycle(model.layernorm_z_cycle(z))
                    z = z + model.template_embedder(batch, z)
                    z = model.msa_module(msa_raw, z, s_inputs, msa_mask, pair_mask,
                                          msa_chunk_size=2048)
                    s = s_init + model.linear_s(model.layernorm_s(s))
                    s, z = model.pairformer(s, z, mask=mask, pair_mask=pair_mask)

                torch.manual_seed(SEED)  # fresh for diffusion noise
                coords = model.diffusion.sample(
                    ref_pos=batch["ref_coords"],
                    ref_charge=ref_charge,
                    ref_features=ref_features,
                    atom_to_token=batch["atom_to_token"],
                    atom_mask=atom_mask,
                    s_trunk=s, z_trunk=z, s_inputs=s_inputs,
                    relpe_feats=relpe_feats,
                    ref_space_uid=batch.get("ref_space_uid"),
                )
        finally:
            model.diffusion.n_steps = orig_steps
        return {"coords": coords}

    def test_coords_statistics(self, snapshot, actual):
        """Diffusion inherits cuDNN non-determinism (two identical runs can
        drift by tens of Å in atom coords). Bit-for-bit comparison is
        unrealistic; instead we pin distributional stats — mean, std,
        per-atom radius. A genuine refactor bug would shift these.
        """
        a = actual["coords"].detach().to(dtype=torch.float32, device="cpu").numpy()
        e = snapshot["coords"]
        assert a.shape == e.shape
        # Compare statistics. Tolerances are generous because stochastic
        # coords vary run-to-run; a real numerical regression would typically
        # move these metrics by >50%.
        for name, a_val, e_val in [
            ("mean",    a.mean(),              e.mean()),
            ("std",     a.std(),               e.std()),
            ("abs_max", np.abs(a).max(),       np.abs(e).max()),
            ("centre_x", a.reshape(-1, 3).mean(0)[0],
                         e.reshape(-1, 3).mean(0)[0]),
            ("centre_y", a.reshape(-1, 3).mean(0)[1],
                         e.reshape(-1, 3).mean(0)[1]),
            ("centre_z", a.reshape(-1, 3).mean(0)[2],
                         e.reshape(-1, 3).mean(0)[2]),
        ]:
            scale = max(abs(e_val), 1.0)
            rel = abs(a_val - e_val) / scale
            assert rel < 0.5, (
                f"diffusion {name}: actual {a_val:.3f} vs snapshot {e_val:.3f} "
                f"(relative diff {rel:.3f} > 0.5 threshold)"
            )


# ---------------------------------------------------------------------------
# Feature-builder snapshot (model/features.py)
# ---------------------------------------------------------------------------

class TestBuildHelpersSnapshot:
    """Pin outputs of the free functions in ``helico.model.features``
    (build_ref_features, build_msa_raw, build_relpe_feats, build_s_inputs).
    Catches any refactor that changes how the batch dict is translated
    into submodule-shaped tensors."""

    @pytest.fixture(scope="class")
    def snapshot(self):
        path = SNAPSHOTS_DIR / "build_helpers.npz"
        assert path.exists(), f"Regenerate with scripts/pm/regenerate_snapshots.py"
        return dict(np.load(path))

    @pytest.fixture(scope="class")
    def actual(self, protenix_model, canonical_batch):
        model = protenix_model
        batch = canonical_batch
        with torch.no_grad(), torch.amp.autocast("cuda", dtype=torch.bfloat16):
            ref_charge, ref_features = build_ref_features(batch)
            atom_mask = batch.get("atom_mask",
                                   torch.ones(1, batch["atom_coords"].shape[1], device=DEVICE))
            atom_mask = atom_mask.float()
            s_inputs = build_s_inputs(model.input_embedder, batch, ref_charge, ref_features, atom_mask)
            relpe_feats = build_relpe_feats(batch)
            msa_raw, _ = build_msa_raw(batch)
        return {
            "ref_charge": ref_charge, "ref_features": ref_features,
            "s_inputs": s_inputs, "msa_raw": msa_raw,
            **{f"relpe_{k}": v for k, v in relpe_feats.items()},
        }

    def test_ref_charge(self, snapshot, actual):
        _assert_matches(actual["ref_charge"], snapshot["ref_charge"], "ref_charge")

    def test_ref_features(self, snapshot, actual):
        _assert_matches(actual["ref_features"], snapshot["ref_features"],
                        "ref_features")

    def test_s_inputs(self, snapshot, actual):
        _assert_matches(actual["s_inputs"], snapshot["s_inputs"], "s_inputs")

    def test_msa_raw(self, snapshot, actual):
        _assert_matches(actual["msa_raw"], snapshot["msa_raw"], "msa_raw")

    def test_relpe_residue_index(self, snapshot, actual):
        _assert_matches(actual["relpe_residue_index"],
                        snapshot["relpe_residue_index"], "relpe_residue_index")

    def test_relpe_token_index(self, snapshot, actual):
        _assert_matches(actual["relpe_token_index"],
                        snapshot["relpe_token_index"], "relpe_token_index")

    def test_relpe_asym_id(self, snapshot, actual):
        _assert_matches(actual["relpe_asym_id"],
                        snapshot["relpe_asym_id"], "relpe_asym_id")

    def test_relpe_entity_id(self, snapshot, actual):
        _assert_matches(actual["relpe_entity_id"],
                        snapshot["relpe_entity_id"], "relpe_entity_id")

    def test_relpe_sym_id(self, snapshot, actual):
        _assert_matches(actual["relpe_sym_id"],
                        snapshot["relpe_sym_id"], "relpe_sym_id")


# ---------------------------------------------------------------------------
# Fast 1MBN end-to-end correctness test
# ---------------------------------------------------------------------------

class TestFold1MBNFast:
    """Fold 1MBN with aggressive speed settings (1 sample, 3 cycles, 20
    diffusion steps) and assert looser correctness thresholds than
    TestFoldRealProtein. Takes ~30-60 sec instead of 7 min, so it can run
    on every refactor commit.

    Purpose: catch end-to-end regressions the trunk snapshot can't see —
    e.g. confidence-head numerics, diffusion-module wiring, post-processing.
    Not meant as a correctness proof; that's what the full-quality
    TestFoldRealProtein in test_model.py provides.
    """

    @pytest.fixture(scope="class")
    def model_fast(self):
        ckpt = torch.load(CHECKPOINT, map_location="cpu", weights_only=False)
        sd = ckpt["model"]
        sd = OrderedDict((k.removeprefix("module."), v) for k, v in sd.items())
        model = Helico(HelicoConfig())
        load_protenix_state_dict(sd, model)
        # Shrink diffusion step count at the module level
        model.diffusion.n_steps = 20
        return model.to(device=DEVICE).eval()

    @pytest.fixture(scope="class")
    def metrics(self, model_fast):
        """Run predict_target with fast settings; return CA RMSD, pLDDT, pTM."""
        from helico.data import parse_ccd, parse_mmcif, parse_a3m, a3m_to_msa_matrix, compute_msa_features
        from helico.bench import (
            structure_to_chains, predict_target, match_atoms,
            extract_backbone_coords, compute_rmsd,
        )

        assert CIF_PATH.exists(), f"Missing {CIF_PATH}"
        assert A3M_PATH.exists(), f"Missing {A3M_PATH}"

        ccd = parse_ccd(cache_path=CCD_CACHE if CCD_CACHE.exists() else None)
        gt_structure = parse_mmcif(CIF_PATH)
        seqs, _ = parse_a3m(A3M_PATH.read_text())
        msa, dels = a3m_to_msa_matrix(seqs)
        msa_feat = compute_msa_features(msa, dels)
        chains = structure_to_chains(gt_structure)

        torch.manual_seed(SEED)
        out = predict_target(
            model_fast, chains, ccd,
            msa_features=msa_feat,
            n_samples=1, device=DEVICE, dtype=torch.bfloat16, n_cycles=3,
        )
        assert out is not None, "predict_target returned None"
        tokenized, results = out

        pred_coords = results["coords"][0].cpu().float().numpy()
        matched = match_atoms(tokenized, pred_coords, gt_structure)
        pred_bb, gt_bb, _ = extract_backbone_coords(matched)
        return {
            "ca_rmsd": compute_rmsd(pred_bb, gt_bb),
            "mean_plddt": results["plddt"][0].mean().item(),
            "ptm": results["ptm"][0].item(),
            "n_backbone_atoms": len(pred_bb),
        }

    def test_ca_rmsd_loose(self, metrics):
        """CA RMSD loose threshold. Full test in test_model.py uses 1.0 Å
        with 10 samples; here we allow 4.0 Å since we're using 1 sample,
        3 cycles, 20 diffusion steps."""
        assert metrics["ca_rmsd"] < 4.0, (
            f"CA RMSD {metrics['ca_rmsd']:.2f} Å exceeds 4.0 Å — "
            f"end-to-end pipeline may have regressed"
        )

    def test_plddt_reasonable(self, metrics):
        """Mean pLDDT > 60 (full test uses 80)."""
        assert metrics["mean_plddt"] > 60.0, (
            f"Mean pLDDT {metrics['mean_plddt']:.1f} < 60 — "
            f"model is very unconfident; confidence head may have regressed"
        )

    def test_ptm_in_range(self, metrics):
        """pTM in [0, 1]."""
        assert 0.0 <= metrics["ptm"] <= 1.0, f"pTM {metrics['ptm']:.3f} outside [0, 1]"

    def test_matched_ca_atoms(self, metrics):
        """1MBN = 153 residues → extract_backbone_coords returns 153 CAs.
        Any number substantially below 150 means tokenization or atom
        matching has regressed."""
        assert metrics["n_backbone_atoms"] > 140, (
            f"Only {metrics['n_backbone_atoms']} CA atoms matched — "
            f"expected ~153 for 1MBN"
        )
