"""Regenerate docs/benchmarks.md from committed experiment summary CSVs.

Usage:
    uv run python scripts/pm/plot_bench.py
    uv run python scripts/pm/plot_bench.py --check   # non-zero exit if stale

Scans `experiments/exp*/data/summary.csv` — the bench summary each
experiment notebook saves during its analysis cells — and produces a
single docs/benchmarks.md page with three comparison tables: mean LDDT,
mean DockQ, and success rate. Each column is one experiment.

Uses stdlib `csv` only (no pandas) so it runs in any env including
CI without extra deps.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parents[2]
REPO_SLUG = "Open-Athena/helico"

BENCH_CATEGORIES = [
    "monomer_protein", "monomer_dna", "monomer_rna",
    "interface_protein_protein", "interface_antibody_antigen",
    "interface_protein_peptide", "interface_protein_ligand",
    "interface_protein_dna", "interface_protein_rna",
]

_INTERFACE = [c for c in BENCH_CATEGORIES if c.startswith("interface_")]


def find_bench_summaries() -> list[tuple[str, Path]]:
    """Return [(experiment_slug, summary.csv path)] sorted by slug desc."""
    out: list[tuple[str, Path]] = []
    exp_root = REPO_ROOT / "experiments"
    if not exp_root.is_dir():
        return out
    for exp_dir in exp_root.iterdir():
        if not exp_dir.is_dir() or not exp_dir.name.startswith("exp"):
            continue
        summary = exp_dir / "data" / "summary.csv"
        if summary.exists():
            out.append((exp_dir.name, summary))
    # Highest issue number first
    out.sort(key=lambda p: -_issue_num_from_slug(p[0]))
    return out


def _issue_num_from_slug(slug: str) -> int:
    head = slug.split("_", 1)[0]
    digits = head[3:]
    return int(digits) if digits.isdigit() else 0


def read_summary(path: Path) -> dict[str, dict[str, str]]:
    """Read a summary.csv into {category: row_dict}."""
    out: dict[str, dict[str, str]] = {}
    with open(path) as f:
        for row in csv.DictReader(f):
            out[row["category"]] = row
    return out


def _fmt(val: str, decimals: int = 3) -> str:
    if val is None or val == "" or val.lower() == "nan":
        return "—"
    try:
        return f"{float(val):.{decimals}f}"
    except ValueError:
        return val


def _table(
    title: str,
    prose: str,
    categories: list[str],
    summaries: list[tuple[str, dict[str, dict[str, str]]]],
    column: str,
    decimals: int,
) -> list[str]:
    """Render a markdown section with one column per experiment."""
    lines = [f"## {title}", "", prose, ""]
    if not summaries:
        lines.append("_(No summaries yet.)_")
        return lines

    headers = ["category"] + [slug for slug, _ in summaries]
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join("---" for _ in headers) + "|")
    for cat in categories:
        row_cells = [f"`{cat}`"]
        for slug, bench in summaries:
            row = bench.get(cat)
            row_cells.append(_fmt(row[column], decimals) if row else "—")
        lines.append("| " + " | ".join(row_cells) + " |")
    return lines


def render_benchmarks(summaries: list[tuple[str, Path]]) -> str:
    bench_by_slug: list[tuple[str, dict]] = [
        (slug, read_summary(path)) for slug, path in summaries
    ]

    lines = [
        "# Benchmarks",
        "",
        "Cross-experiment comparison tables computed from the bench",
        "summary CSVs committed under each `experiments/exp<N>_*/data/`",
        "directory.",
        "",
        "_This page is generated by `scripts/pm/plot_bench.py` from each_",
        "_experiment's `data/summary.csv`._",
        "",
    ]

    if not summaries:
        lines.extend([
            "_No experiment summaries committed yet — this page will_",
            "_populate as experiments complete and their `summary.csv` lands_",
            "_under `data/`._",
        ])
        return "\n".join(lines) + "\n"

    lines.extend(
        _table(
            title="Mean LDDT",
            prose="Higher is better. Dashes indicate the category wasn't scored in that run.",
            categories=BENCH_CATEGORIES,
            summaries=bench_by_slug,
            column="mean_lddt",
            decimals=3,
        )
    )
    lines.append("")
    lines.extend(
        _table(
            title="Mean DockQ (interface categories)",
            prose=(
                "Higher is better. DockQ isn't defined for monomers or the "
                "ligand interface category (which uses LDDT-PLI + LRMSD instead)."
            ),
            categories=[c for c in _INTERFACE if c != "interface_protein_ligand"],
            summaries=bench_by_slug,
            column="mean_dockq",
            decimals=3,
        )
    )
    lines.append("")
    lines.extend(
        _table(
            title="Success rate (%)",
            prose=(
                "Non-ligand interface success: DockQ ≥ 0.23. "
                "Ligand interface success: LDDT-PLI > 0.8 AND LRMSD < 2.0 Å."
            ),
            categories=_INTERFACE,
            summaries=bench_by_slug,
            column="success_pct",
            decimals=1,
        )
    )
    lines.append("")

    lines.extend([
        "## Source data",
        "",
        "Each column above is read from the corresponding experiment's",
        "committed `data/summary.csv`:",
        "",
    ])
    for slug, path in summaries:
        rel = path.relative_to(REPO_ROOT).as_posix()
        url = f"https://github.com/{REPO_SLUG}/blob/main/{rel}"
        lines.append(f"- `{slug}`: [`{rel}`]({url})")

    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--output", type=Path,
        default=REPO_ROOT / "docs" / "benchmarks.md",
    )
    ap.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if the existing file is stale; don't write.",
    )
    args = ap.parse_args(argv)

    summaries = find_bench_summaries()
    content = render_benchmarks(summaries)

    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current.strip() != content.strip():
            print(f"STALE: {args.output}", file=sys.stderr)
            print("Regenerate with: uv run python scripts/pm/plot_bench.py",
                  file=sys.stderr)
            return 1
        print(f"up to date: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    print(f"wrote {args.output} ({len(summaries)} summaries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
